### ISSUE TITLE
Serve with Nginx instead of Haproxy

### ISSUE THREAD

**Issue by coanghel** [pfh59/eve-whmapper#313]
I'm having an issue trying to serve this with Nginx (which is currently serving as a reverse proxy for several apps and already bound to the 443 port).

If I do not include a location block for /sso/callback I receive a generic Nginx 502 after logging in with my character; nothing is in the wh-mapper container logs. The URL displayed includes a code and state and if I try to manually refresh I see the below error in the container log and Nginx serves an ASPNet error page from the wh-mapper app.

```
2024-11-10T05:44:53.904213654Z [2024-11-10 05:44:53] fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
2024-11-10T05:44:53.904250454Z       An unhandled exception has occurred while executing the request.
2024-11-10T05:44:53.904254174Z       Microsoft.AspNetCore.Authentication.AuthenticationFailureException: An error was encountered while handling the remote login.
2024-11-10T05:44:53.904257334Z        ---> Microsoft.AspNetCore.Authentication.AuthenticationFailureException: OAuth token endpoint failure: invalid_grant;Description=Authorization code is invalid.
2024-11-10T05:44:53.904260734Z          --- End of inner exception stack trace ---
2024-11-10T05:44:53.904263254Z          at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
2024-11-10T05:44:53.904266454Z          at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2024-11-10T05:44:53.904269094Z          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
```

If I define my /sso/callback location block I instead am brought to an ASPNet error page and see the below in the container logs

```
2024-11-10T06:00:12.565844800Z [2024-11-10 06:00:12] fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
2024-11-10T06:00:12.565908400Z       An unhandled exception has occurred while executing the request.
2024-11-10T06:00:12.565912720Z       Microsoft.AspNetCore.Authentication.AuthenticationFailureException: An error was encountered while handling the remote login.
2024-11-10T06:00:12.565941840Z        ---> Microsoft.AspNetCore.Authentication.AuthenticationFailureException: The oauth state was missing or invalid.
2024-11-10T06:00:12.565945600Z          --- End of inner exception stack trace ---
2024-11-10T06:00:12.565948480Z          at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
2024-11-10T06:00:12.565951240Z          at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2024-11-10T06:00:12.565954080Z          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
```

I was able to get this deployed fine with Haproxy, but I need to use Nginx for my environment.

**Comment by coanghel** [comment]
Turns out this was due to nginx config related to the response header sizes; the default is too small for the EVE ESI OAuth flow. This can be corrected by adding the below to the proxy config:

```
    proxy_buffer_size 16k;
    proxy_buffers 4 32k;
    proxy_busy_buffers_size 64k;
```

**Comment by coanghel** [comment]
Docker. My wh-mapper and nginx reverse proxy are separate containers.
