### ISSUE TITLE
An error has occurred

### ISSUE THREAD

**Issue by pfh59** [pfh59/eve-whmapper#77]
**Describe the bug**
An error has occurred randomly

**To Reproduce**
1. Click on system main
3. Click in empty zone

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Mac OSx Ventura 13.3.1a
 - Browser:Safari
 - Version: 16.4

**Additional context**
Log Error:
```
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
whmapper_1  |       Unhandled exception in circuit '_usI0UPtGqMrPyNM5xnHZSKB5TSaXe8mc1Zi4Alt_qc'.
whmapper_1  |       System.AggregateException: Exceptions were encountered while disposing components. (Value cannot be null. (Parameter 'source')) (Value cannot be null. (Parameter 'source')) (Value cannot be null. (Parameter 'source')) (Value cannot be null. (Parameter 'source')) (Value cannot be null. (Parameter 'source'))
whmapper_1  |        ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
whmapper_1  |          at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
whmapper_1  |          at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
whmapper_1  |          at MudBlazor.MudTable`1.get_FilteredItems()
whmapper_1  |          at MudBlazor.MudTable`1.ContainsItem(Object item)
whmapper_1  |          at MudBlazor.TableContext`1.Remove(MudTr row, Object item)
whmapper_1  |          at Microsoft.AspNetCore.Components.Rendering.ComponentState.TryDisposeInBatch(RenderBatchBuilder batchBuilder, Exception& exception)
```

**Comment by pfh59** [comment]
You need to have signatures in selected WH, if you click in empty zone Signatures value is null => error with Tables
